// IncidentLens realistic seed data
CREATE
(team:Team {id:'TEAM-PLATFORM', name:'Platform Team'}),
(team2:Team {id:'TEAM-PAYMENTS', name:'Payments Team'}),
(svc:Service {id:'SVC-PAY', name:'Payment Service'}),
(svc2:Service {id:'SVC-AUTH', name:'Authentication Service'}),
(app:Application {id:'APP-PAY', name:'Payment API'}),
(app2:Application {id:'APP-AUTH', name:'Auth API'}),
(srv:Server {id:'SRV-PROD-01', name:'PROD-SRV-01'}),
(srv2:Server {id:'SRV-PROD-02', name:'PROD-SRV-02'}),
(comp:Component {id:'CMP-DB', name:'Payment Database'}),
(comp2:Component {id:'CMP-REDIS', name:'Redis Cache'}),
(chg:Change {id:'CHG-204', name:'Payment DB connection pool change', date:'2026-08-25'}),
(chg2:Change {id:'CHG-205', name:'Auth API deployment', date:'2026-08-26'}),
(i1:Incident {id:'INC-1042', title:'Payment Service Unavailable', severity:'HIGH', status:'RESOLVED', description:'Payment requests failed because database connections were exhausted.'}),
(i2:Incident {id:'INC-1041', title:'Payment API Latency', severity:'MEDIUM', status:'RESOLVED', description:'Payment API experienced elevated latency.'}),
(i3:Incident {id:'INC-1038', title:'Authentication Errors', severity:'HIGH', status:'RESOLVED', description:'Users received intermittent authentication failures.'}),
(i4:Incident {id:'INC-1031', title:'Payment Database Timeout', severity:'HIGH', status:'RESOLVED', description:'Database queries timed out during peak traffic.'}),
(i5:Incident {id:'INC-1022', title:'Redis Cache Miss Spike', severity:'LOW', status:'RESOLVED', description:'Cache misses increased after a deployment.'}),
(i1)-[:AFFECTS]->(svc),
(i2)-[:AFFECTS]->(svc),
(i4)-[:AFFECTS]->(svc),
(i3)-[:AFFECTS]->(svc2),
(i5)-[:AFFECTS]->(svc2),
(svc)-[:USES]->(app),
(svc2)-[:USES]->(app2),
(app)-[:RUNS_ON]->(srv),
(app2)-[:RUNS_ON]->(srv2),
(srv)-[:CONTAINS]->(comp),
(srv2)-[:CONTAINS]->(comp2),
(svc)-[:OWNED_BY]->(team2),
(svc2)-[:OWNED_BY]->(team),
(i1)-[:CAUSED_BY]->(chg),
(i3)-[:CAUSED_BY]->(chg2),
(chg)-[:MODIFIES]->(app),
(chg2)-[:MODIFIES]->(app2),
(i1)-[:RELATED_TO]->(i2),
(i1)-[:RELATED_TO]->(i4),
(i3)-[:RELATED_TO]->(i5)
RETURN count(*) AS created_items;